language: python
python:
  - "2.7"
# nightly gets the latest nightly version of python... python 3 in the case. For now I don't want that!
#  - "nightly"
# command to install dependencies
#install:
#  - pip install -r requirements.txt
# command to run tests
script:
  - pwd
  - ls -la
  - cp tests/uploadr.ini .
  - cat uploadr.ini
  - export PYTHONPATH=$PYTHONPATH:..
  - pytest --flakes
  - pytest -v # or py.test for Python versions 3.5 and below
# is this commmand necessary or if you have test_*.txt it will automatically run?
  - pytest --doctest-modules # Attempt to run test_*.txt with doctest
# force running 
  - pytest --doctest-modules -v tests/test_isThisStringUnicode.txt # Attempt to run test_*.txt with doctest
