# =============================================================================
# Use travis settings maximum_number_of_builds --set 1 as the builds envs depend on flickr
# =============================================================================
# language
language: python
python:
  - "2.7"
  - "3.6"
#  - "3.7-dev"   # Comment for faster test
# nightly gets the latest nightly version of python... python 3 in the case. For now I don't want that!
#  - "nightly"

before_install:
# For use with wget into github account
  - echo -e "machine github.com\n  login $CI_USER\n  password $CI_USER_PASSWORD" >> ~/.netrc

  - echo -e "files:\n  - /home/travis/build/oPromessa/flickr-uploader/nohup.err\n  - /home/travis/build/oPromessa/flickr-uploader/nohup.log\ndestination:\n  $PT_HOSTNAME\n  $PT_PORT\n  $PT_PROTOCOL\n" > ~/syslog2.yml
  - cat ~/syslog2.yml

# =============================================================================
# command to install dependencies
install:
  - pip install -r requirements.txt
# Get deletr. For future use to delete all pics frmo Flickr prior to a run
  - wget https://github.com/oPromessa/flickr-deletr/archive/master.tar.gz -O flickr-deletr-master.tar.gz
  - tar zxvf flickr-deletr-master.tar.gz
# Get papertrail.com remote_syslog2
  - wget https://github.com/papertrail/remote_syslog2/releases/download/v0.19/remote_syslog_linux_i386.tar.gz -O remote_syslog_linux_i386.tar.gz
  - tar zxvf remote_syslog_linux_i386.tar.gz
  #- ls -la remote_syslog
  #- ls -la

# =============================================================================
# env
env:
  global:
    - PYTHONPATH=..:.
    - LC_ALL=en_US.utf8
    - LANG=en_US.utf8
# Set to -v for Verbose option of uploadr
    - VerboseVar=-v
    - BadFilesVar=-b
    - ExcludedVar=--remove-excluded
    - TAIL_LINES=200  # Tail $TAIL_LINES for output logging. Default: 20
    - WAIT_TIME=2     # Sleep time between first and second run
# Delete !!!!!!!!!!!!!!!!!!! CAREFULL !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# To ensure an empty Flickr database. Set DeleteAllFromFlickr=1. 0 otherwise.
    - DeleteAllFromFlickr=0
  matrix:
# TestScenario: Help, Delete DryRun, BadFiles, MultiProcessing, Remove, Replace, RemoveReplace
# Help
    - TestScenario=Help UploadrOptions="$VerboseVar --help" DeleteAllFromFlickr=1
# DryRun
    #- TestScenario=DryRun UploadrOptions="$VerboseVar -n"
# Badfiles
    #- TestScenario=BadFiles UploadrOptions="$VerboseVar $BadFilesVar"
# Multiprocessing
    - TestScenario=MultiProcessing UploadrOptions="$VerboseVar $BadFilesVar -p 20"
# addAlbumsMigrate. Option --add-albums-migrate is added on SECOND RUN
    - TestScenario=addAlbumsMigrate UploadrOptions="$VerboseVar $BadFilesVar -p 20"
# RemoveReplace, Multiprocessing. Also test cleaning up badfiles database entries
    - TestScenario=RemoveReplace UploadrOptions="$VerboseVar $BadFilesVar -p 10 -c"
# ExcludedFolders+IgnoredFiles in Single Processing mode. Also test cleaning up badfiles database entries
    - TestScenario=ExcludedFolders UploadrOptions="$VerboseVar $BadFilesVar $ExcludedVar -c"
# =============================================================================
# before_script
# Get database token ready
# Get uploadr.ini from tests
# Use environment secure variable for private settings
before_script:
  - pwd
  - pythonVersion=`python -V 2>&1 | cut -d\  -f2`
  - echo $pythonVersion
  - echo Travis Python Version
  - echo ${TRAVIS_PYTHON_VERSION}  
#  - ls -laR
  - cp tests/uploadr.ini .
  - cp tests/uploadr.ini /home/travis/virtualenv/python$pythonVersion/bin/uploadr.ini || cp tests/uploadr.ini /home/travis/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/uploadr.ini
  - grep FILES_DIR uploadr.ini
#  - cat uploadr.ini
  - echo "INSERT INTO oauth_tokens ( api_key, lookup_key, oauth_token, oauth_token_secret, access_level, fullname, username, user_nsid) VALUES ( '"$api_key"', '', '"$oauth_token"', '"$oauth_token_secret"', 'delete', '"$fullname"', '"$username"', '"$user_nsid"');" | sqlite3 token/oauth-tokens.sqlite
  - sqlite3 token/oauth-tokens.sqlite 'SELECT * FROM oauth_tokens;'
  - find "./tests/Test Photo Library" -type f -exec md5sum '{}' \;
  - remote_syslog/remote_syslog -c ~/syslog2.yml


# =============================================================================
# run script for tests
script:
# DELETE RUN ------------------------------------------------------------------
# !!!!!!!!!!!!!!!!!!!!!!!!!! CAREFULL !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# COMPATIBLE WITH PYTHON 2.7 ONLY
  - if [[ $TRAVIS_PYTHON_VERSION == 2* && $DeleteAllFromFlickr == 1 ]]; then cp flickr-deletr-master/tests/uploadr.ini flickr-deletr-master/uploadr.ini; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* && $DeleteAllFromFlickr == 1 ]]; then cp token/oauth-tokens.sqlite flickr-deletr-master/token/oauth-tokens.sqlite; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2* && $DeleteAllFromFlickr == 1 ]]; then coverage run -a --concurrency multiprocessing ./flickr-deletr-master/delete.py; fi

# First RUN -------------------------------------------------------------------
  - coverage run -a --concurrency multiprocessing uploadr.py $VerboseVar $UploadrOptions > /home/travis/build/oPromessa/flickr-uploader/nohup.log 2> /home/travis/build/oPromessa/flickr-uploader/nohup.err
  - tail -$TAIL_LINES /home/travis/build/oPromessa/flickr-uploader/nohup.log
  - tail -$TAIL_LINES /home/travis/build/oPromessa/flickr-uploader/nohup.err

  - coverage combine
  - coverage report -m uploadr.py

# DB OUTPUT for REFERENCE RUN#1------------------------------------------------
  - if [[ $TestScenario != Help ]]; then sqlite3 flickrdb "SELECT *, datetime( last_modified, 'unixepoch', 'localtime') FROM files ORDER BY path;"; fi
  - if [[ $TestScenario != Help ]]; then sqlite3 flickrdb 'SELECT * FROM badfiles ORDER BY path;'; fi
  - if [[ $TestScenario != Help ]]; then sqlite3 flickrdb 'SELECT * FROM sets ORDER BY name;'; fi
  - if [[ $TestScenario != Help ]]; then sqlite3 flickrdb 'SELECT sets.set_id, sets.name, count(*) FROM sets, files WHERE sets.set_id = files.set_id GROUP BY 1, 2 ORDER BY 2;'; fi
  - if [[ $TestScenario != Help ]]; then sqlite3 flickrdb 'SELECT sets.set_id, sets.name, files_id, path FROM sets, files WHERE sets.set_id = files.set_id ORDER BY sets.name, path;'; fi

# WAIT TINE BEFORE SECOND RUN -------------------------------------------------
  - sleep $WAIT_TIME

# Second RUN: Remove, Replace, RemoveReplace, ExcludedFolders, addAlbumsMigrate
  - if [[ $TestScenario == addAlbumsMigrate ]]; then sqlite3 flickrdb 'PRAGMA user_version="2"'; fi
  - if [[ $TestScenario == addAlbumsMigrate ]]; then export UploadrOptions="$UploadrOptions --add-albums-migrate"; echo $UploadrOptions; fi

  - if [[ $TestScenario == RemoveReplace ]]; then rm "./tests/Test Photo Library/photo.jpg"; fi
  - if [[ $TestScenario == RemoveReplace ]]; then rm "./tests/Test Photo Library/photo_Excepção.jpg"; fi
  - if [[ $TestScenario == RemoveReplace ]]; then cp "./tests/Test Photo Library/ReplaceTest/file_34_Substituição.ForReplace" "./tests/Test Photo Library/Pics.Replaced/file_34_Substituição.jpg"; fi
  - if [[ $TestScenario == RemoveReplace ]]; then cp "./tests/Test Photo Library/ReplaceTest/file_35.jpg.ForReplace" "./tests/Test Photo Library/Pics.Replaced/file_35.jpg"; fi

  - if [[ $TestScenario == ExcludedFolders ]]; then cp ./tests/uploadr_excluded.ini ./uploadr.ini; fi

  - coverage run -a --concurrency multiprocessing uploadr.py $VerboseVar $UploadrOptions >> /home/travis/build/oPromessa/flickr-uploader/nohup.log 2>> /home/travis/build/oPromessa/flickr-uploader/nohup.err
  - tail -$TAIL_LINES /home/travis/build/oPromessa/flickr-uploader/nohup.log
  - tail -$TAIL_LINES /home/travis/build/oPromessa/flickr-uploader/nohup.err

  - coverage combine
  - coverage report -m uploadr.py
  - sleep $WAIT_TIME

# pytest --flakes (Code analysis) ---------------------------------------------
# FOR NOW WITH PYTHON 2.* Versions only. Will edit tests for PYTHON 3.* Versions
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pytest -v --flakes; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pytest -v --flakes tests/test_StrUni.py::test_Unicode tests/test_StrUni.py::test_RUN tests/test_sys_argv.txt::test_sys_argv.txt; fi

# FOR NOW WITH PYTHON 2.* Versions only. Will edit tests for PYTHON 3.* Versions
#  - pytest -v # or py.test for Python versions 3.5 and below
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pytest --doctest-modules; fi # Attempt to run test_*.txt with doctest
#  - pytest --doctest-modules # Attempt to run test_*.txt with doctest

# Deleted Pics Non existant on FLickr -----------------------------------------
# For testing a local deleted file also not available in flickr
# - sleep $WAIT_TIME
# Test Deleted file
#  - coverage run -a uploadr.py $VerboseVar -bl 10
#  - coverage report -m uploadr.py
#  - sqlite3 flickrdb "SELECT *, datetime( last_modified, 'unixepoch', 'localtime') FROM files;"

after_script:
# MD5SUM Output for REFERENCE -------------------------------------------------
#  - if [[ $TestScenario == RemoveReplace ]]; then find "./tests/Test Photo Library" -type f -exec md5sum '{}' \; ; fi

# DB OUTPUT for REFERENCE RUN#2------------------------------------------------
  - sqlite3 flickrdb "SELECT *, datetime( last_modified, 'unixepoch', 'localtime') FROM files ORDER BY path;"
  - sqlite3 flickrdb 'SELECT * FROM badfiles ORDER BY path;'
  - sqlite3 flickrdb 'SELECT * FROM sets ORDER BY name;'
  - sqlite3 flickrdb 'SELECT sets.set_id, sets.name, count(*) FROM sets, files WHERE sets.set_id = files.set_id GROUP BY 1, 2 ORDER BY 2;'
  - sqlite3 flickrdb 'SELECT sets.set_id, sets.name, files_id, path FROM sets, files WHERE sets.set_id = files.set_id ORDER BY sets.name, path;'

# Deploy to Heroku ------------------------------------------------------------
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  #app: uploadr-showcase
  on:
    branch: master
    #branch: do-not-load-duplicates
    #repo: oPromessa/flickr-uploadr
